language: ruby
rvm:
- 1.9.3
bundler_args: --without development
services:
- mongodb
- redis-server
gemfile:
- Gemfile
script: rake install && 
  mob decode -p 'git_ssh_' -l 22 -f git_ssh_test.ssh && chmod 0400 git_ssh_test.ssh && 
  export MOB_TEST_OWNER_GITHUB_SSH_KEY_PATH="$(pwd)/git_ssh_test.ssh" && rake test
notifications:
  recipients:
  - mobilize.server@gmail.com
branches:
  only:
  - master
env:
  global:
#mob_test_google_login
  - "MOB_TEST_GOOGLE_LOGIN=mobilize.server@gmail.com"
#mob_test_user_id
  - "MOB_TEST_USER_ID=mobilize.server@gmail.com"
#mob_test_github_login
  - "MOB_TEST_GITHUB_LOGIN=mobilize"
#mob_test_owner_github_login
  - "MOB_TEST_OWNER_GITHUB_LOGIN=mobilize"
#mob_test_owner_github_password
  - secure: "fatwGEFiDXpcgcIk6TUZpyP4mJcEY/uTHXO5ZMWBorcznJ7dxb12UjUDsyl3EFnG3v4s/MThGGNx9mhmb1OnClO+oHUim1TB3OAvHGF3WOM03rwnGMTvkV4VVIpEXc5bOzE8fSWn02X9Guiv6Sh5ycA1T7wpf5Pr6Xgja6Hi99g="
#mob_test_private_github_domain
  - "MOB_TEST_PRIVATE_GITHUB_DOMAIN='github.com'"
#mob_test_private_github_owner
  - "MOB_TEST_PRIVATE_GITHUB_OWNER='mobilize'"
#mob_test_private_github_repo
  - secure: "U8WspBw8NQRekwYrZOYrfUeV4qgaWscQy8izTtlHJmqaZ4hI89itzIA69GWA9p0ouwoXgubY1jXVPJgWkZsPvXTWPjw2TH8Kt8lk6l8po0NT7SPpq3ic+c4KScWfITZYGSisVc9A3WU589xCXBWMV4y27IpUWZ0rMatBikybFjs="
#mob_test_aws_access_key_id
  - secure: "Q2PEzjUV7yJNKpShRsgt6zym1cPh8+OxYpFaw736FuRIAiy3llvIua9P6wM4yRpk2DFnn7r2WUfemEDL7/NXUucr6rXrdAmlUaHmObn3r1Y1rLQEQrYRaUe1hadEKkHzH+cR0Fbwl7/E/Rwr/Qjs/hkTF5jYQOOyjMD94mM4jEE="
#mob_test_aws_secret_access_key
  - secure: "J3IFzH1IWuIxWV6R8B6Ko/wIIX0xaTkEJc03Q77F68n7WCo9lkWIibJE7XddCbimthDFR7K+L2CxVctNTIqgzKjQnwxxck6fM6td41C7UgrylL0kvEBm/rCx7uAzuUinQXGHN/18r4QIZDWVDQ7u+bOaMCttiGzBjJjoPo2XQzg="
#mob_test_ec2_def_region
  - "MOB_TEST_EC2_DEF_REGION='us-west-1'"
#mob_test_ec2_name
  - "MOB_TEST_EC2_NAME='mobilize-test'"
#mob_test_ec2_ami
  - "MOB_TEST_EC2_AMI='ami-fe002cbb'"
#mob_test_ec2_size
  - "MOB_TEST_EC2_SIZE='t1.micro'"
#mob_test_ec2_keypair_name
  - secure: "meMH/Z03JtnPIgkSkUOoJhgsbsM6613w8XMZ8t9p/+P23M9q1ioMhWyzOCluSE9kbOUvcibjPUl4D4cC42KXoeL6Y3y0zO78w5LIxVhCV0OPx9hLPX9CkLWm2ySg0ECQcg4siXP+EZF3NYI/sZm5/LyfT9sgGnyvyopPzBb6qY8="
#mob_test_ec2_sg_names
  - "MOB_TEST_EC2_SG_NAMES='default'"
#git_ssh_00
  - secure: "FnoCpSbl9IhtgmxKBO7iYK8vOtKEr+NJN3F9Pt0up/Ln634VrKM8UvB0jz0uolo5b0idNNHkahry7z5xc3RIUINdbn2lEeshgyph8M+RHg8s/kEtM7XyLP+i932qkCHfaCmZkRBer2pZOKFzav1WrMoF+qGaINudZuq1Hx5EWJ4="
#git_ssh_01
  - secure: "mOZ7OR9GOIqu4mRW6Gdtb0/Jb/ko8WOO1DTDJrlVM/LuHeladjxlsP272tYYJLgEIHUmZ57m9ogR9XjK6oi3j8CyPndxk0eC7+QsQPQFlaXPXdwipxNAAiRutgL5qoIuz6R1LlkMSDC3jK5HrgrPKDLNvkih31OqbRGiXnwAhAI="
#git_ssh_02
  - secure: "Fm8FPeSiw67NZRkfNydi5WJF7hpLI/D26Fr6bUcJQV8dQ6hU6ROKNhES0hHomXO9kcAFWkYMTiYc7+bKmMvHn+qZAIF0mY5IsulSlGrv6FAROSdHoKVelVw8Yj+A/FmWC2Mqom24LwlIz2p3THiQbDHXCH691s5+RxTBzqplKOs="
#git_ssh_03
  - secure: "jUuivHl+MR+igB4cFD36WrQcAWaWtI3XlqYJSUiNyuk7HVPmYS1+13Go7wkf2F7NAoY0xbXqSgT8EJ/hiP2XIBRZfuTkD4Olzwp8s23DTJ7Fzk9yXiSoOvpAbv4AHRyg6AiSjFaGG1SgPIk4wnZlHIjicGn4q/pxCawEfSlmH+k="
#git_ssh_04
  - secure: "TgbGSTrug/nqXtA34PXGjAzzHKzDpKHHTGJ9j9ERC4i942dLUNHOrFdTuwcVxKqWgX/EoixxZSU8r707JF0ZcHg9R08MXxx2jIi5ZCUgqoM0IAwOUBr2QritNkBZ3acSdL2FvHmEWNoVwHoHN1YTj/5rJHUqJeQJuNNYEfxrzbc="
#git_ssh_05
  - secure: "hFpmi0nOPu8aBteMeB5tGbZX4Mh3/1Sy1yW4GvF5UOlT1r2SVnSOPUKAdB9iiIS35Or+XFZ6cJyV64CKczoUcspqhcFY9z/1RpHvYKAnK3H+Ns1EYBhnkp6LAb3NtUz6M/OAM8MiuUBUKi1BoeGxKDZrTflsqT4/NQgoXTjBS/0="
#git_ssh_06
  - secure: "TvLrGiRhqTY8/vmdmELZcnfwWO/zzfTTJA+20tfWXFmYxHEhKGKnX8hm3v6+w+8DV4JlR94opzLEaAbTeVt+mRaB/DPqJkutYHHeRikiWM6eGhBdcaRpRiXcL3pwOFfSv8xmQqnyMD2AsEp3EAZRDjEqz1qVjrA4LfBAa49Z3h0="
#git_ssh_07
  - secure: "ndbIkCxbtBm0l6MHSkZ+GgIKfzT8edXIyhezLbuwdtnM0QbmOrrX1Ma/TU/Eo4kA8IRljzu9+dQmor4pnuy02zh3eWc7IK0uId3CYgP5LnnGdbTRuE4DTdJWQOfmmHlVLcr7XObJUaj7dI8exJHI+4vJQRMBFx05AOG2ZmpNWdA="
#git_ssh_08
  - secure: "SBx5f6UM/ruKHiNmqEeeUFkvDjkTBFbjANYwWXDoHh19pAQn0y3tqOYY1VzYYjGelf7IwQdtR25pZ79ZZgLJvUU9PvsNitkmaJWhLpYdI6xb5AXCwdoHsC0o3yxQ8qv420V8LfHEQaHwfcRsy1+ivv8YWTDTER5/bTHIOOQHY9M="
#git_ssh_09
  - secure: "FmdEG0+HDGYSO6b9RzgJ6t3cX27iLmys28bdKIvt8c4XMeBCWiZv4JxACzuh4WuoKCpVAyHPkTzdsv1R+L75TkFzLRteDhQCLjYEb530qdjR02hhXpJwJkfv1/pCCcacqJ3+TKLkiUWBfIEVE+h5BGVtSbGgn4qAuFEiHWZcqy0="
#git_ssh_10
  - secure: "W5tqkE93t6asczJzI/ockdNQD8JCmLzjqIKO+j3jcSQUr0k450g4P72PeRYo/NdKCxnzUaPnz0U4LvhRry3bZzuiQYxb6/BWu9CDdV8s6liwzBoiZlvUa0DTdA4jUdPJwzJieVhZbD5lMvfAU107kHDn8Naurybf19DT1L2CCA0="
#git_ssh_11
  - secure: "dD+lXErMisM5lUN/pNEQirerKh5yCDRn4syQSrnmPEdfwgyCG6AfGBWw9G7Z/OZP+ajFoyfohbjhdb5exDQsH7vTqqtv4McYcVNblRfU427qYuOdOQj7/Ld1JLAPbW/a6jVdqzzRhkE9yC0ArYzMPOcNpH07aIC/GwJ2e9Gf3ZQ="
#git_ssh_12
  - secure: "M0eVAwiWDGJq730YSTlglbJdrZcjQxjRz9TbaWIGdo6PcfHKUVSkDsgOaeylKnHGnRe2wjFI91VKZOPOq+Ozq1TwXeNo8Bg2nKmz/gG3iaIQ9DYH8/DRXmXLT4O9PINa0/RD2c/ebOr81bZUtzSrqighi4GFcyCIRv0cYfsSbQc="
#git_ssh_13
  - secure: "HNpe2pw5GP/r8qpZLfercU90KZ3qbClYz+pZwec62B8Cpaw+GxRuT9f+efV1I6l8Wt6imbuQuHDDRaVSmnnsYel/h1me/YRwYe82FKimcXkVZZr9bZ6HkT5FDBmzPGUYDVzFgHULAQSbdQgMb4Ai2DwfFf7Ac5bhlSYKkh+eVW8="
#git_ssh_14
  - secure: "E0qoro75Vy5RApmQ80kwbDmCdJT37qUgqgyFCJ3ot7PKVuuuW5AT2IIBQLnjoKCuUEGen33rygnsY04hsQa1VEHNVvprbiVXTVyCUmmSVSY5xtPXd427F9XUpWiaEkVKq7tO+OXODWVe7jjdaioAG2UAaLSHJYQ0upzo3cZpT3w="
#git_ssh_15
  - secure: "fNIjfECN3YZ8HM2BC0ediYlBQoSGE/qjZCSHsYFauCLEdQjwUhk2J5kVwqBNRm/ycpeCPZxZvAbPJyFUrqjWlrAciaZvhzS/3Gzkj2ELbQkv+T3BQTYgbW9P5zMenMjazQsRRdYU8Pdbb64k+Ymy+BhApAZNbBK8ZTr9x2GrLZw="
#git_ssh_16
  - secure: "HH3EUVXaaM/5WQH5IUswB/mAx4WtJyzVcZjBBuH+TvQkzx5j3SEMBIU+01WAHY8616YehVRD8Ynll+9iappZ1p3iSIrsv6/jvnROr+wyw8UZOY3EnhHJx5ag+FQ7n7Ge2I+vTofTcqu9H5R21eoDY+BQT9s/MMM3J4rEvAe9DHc="
#git_ssh_17
  - secure: "XY7kLK48Hf5PaRwEjka5BKIcfZRLdDkW6Ro2tTEDq4nHS53S1yOu/sixOuTvN488InWtDU46xmNfn5IRNledV1oJwVnV2wDQepf0x7bzhqAhTOK2GJVCY1waCC7N5Uahh3lqpIolmk68Uf2SkWaEFMKSRT7TQgvTj5LVIei7Ox4="
#git_ssh_18
  - secure: "P1JRRXeYH7jR2dYzMKq4xBb+swH/ncl3h6fTbfqzZNbjdkSTPYCzG38Li5A4tr6lE5seUtpuV3E+yLx+XcdC6xT9+yNvstjsU+XHE9t16kpY5rqiKCVSldMOjtDRS5GOCBoXNvbANDI6WdzVQXey5rc7gOIS58X4EUmMTV30pjg="
#git_ssh_19
  - secure: "U8zglBPX2k50RufhzY6H+XPyGvkIe50OC5QuMrKe9NX8cUhNQDzO+G6EvGEk7Qq/BHJ4wh8dmvABcBs1PNTEKaAWW9Q7sLkDGqXM079t8B31j8ke54rZK8Mrdd7PDOPxG1f7Bqv/1CVjNcTGsS5wYa3sBjvjYtVB8Y5Ie1Lc9SY="
#git_ssh_20
  - secure: "RmzNBjdoL8gslRCujnluxjguuembMUz+oD6m1ix/PMDw9ctwn66b88wvga9yvqGP/ewURyuLYcFZON/h9FU8FgiYAIQ3LMlnJUV/IgbIzqI/SH+B1rJ/oATQMxNrmsYeM/JRHUtaKUXu6JV7U7I8lLwc+0IuCBMLrTq25eoH15k="
#git_ssh_21
  - secure: "flgZK4uLXgZme410hsXUrcw4Wdi9NvdzkjMZz98e5hXQthF33n//axzPdbUzTGeUkuZxKL8vtjlWEQqwcuAt6DDFPs9WPnIkufcA/TJx2DSpPx7D9YDwaeiqqQqM8smLx7lm7eZ7dwD0aLjP4P4srzv05YJ5JdSGgmEwCtDOM68="
#git_ssh_22
  - secure: "SffVNf/OTB9KVmhSsYwQwEbtsLs8kyfM6OrdYD/RPOPIE3yF5ddYWUF0upjE/SH919Uxgt4Er3DsypUaYWh4zyFLnctPTtRj7vmzlF0aQ6r7SwSMmSDYHYKPNRt+WG+Iy3bi/eHZ+QL2a9mugbqiDLuLX/arA4sqmHyvMkmYv/Q="
