language: ruby
rvm:
- 1.9.3
bundler_args: --without development
services:
- mongodb
- redis-server
gemfile:
- Gemfile
script: rake install && 
  mob decode -p 'git_ssh_' -l 22 -f git_ssh_test.ssh && chmod 0400 git_ssh_test.ssh && 
  mob decode -p 'ec2_ssh_' -l 23 -f ec2_ssh_test.ssh && chmod 0400 ec2_ssh_test.ssh && 
  export MOB_TEST_EC2_PRIV_KEY_PATH="$(pwd)/ec2_ssh_test.ssh" && 
  export MOB_TEST_OWNER_GITHUB_SSH_KEY_PATH="$(pwd)/git_ssh_test.ssh" && 
  rake test
notifications:
  recipients:
  - mobilize.server@gmail.com
branches:
  only:
  - master
env:
  global:
#mob_test_owner_github_password
  - secure: "fatwGEFiDXpcgcIk6TUZpyP4mJcEY/uTHXO5ZMWBorcznJ7dxb12UjUDsyl3EFnG3v4s/MThGGNx9mhmb1OnClO+oHUim1TB3OAvHGF3WOM03rwnGMTvkV4VVIpEXc5bOzE8fSWn02X9Guiv6Sh5ycA1T7wpf5Pr6Xgja6Hi99g="
#mob_test_private_github_repo
  - secure: "U8WspBw8NQRekwYrZOYrfUeV4qgaWscQy8izTtlHJmqaZ4hI89itzIA69GWA9p0ouwoXgubY1jXVPJgWkZsPvXTWPjw2TH8Kt8lk6l8po0NT7SPpq3ic+c4KScWfITZYGSisVc9A3WU589xCXBWMV4y27IpUWZ0rMatBikybFjs="
#mob_test_aws_access_key_id
  - secure: "ecuiyIY1BnOdNVH/C+QUlVFOG44xnXAh4v1Bi/JsqQSuwfdw3UDU52fzNRT9e4ezMNQzLJTgoRNw3TyM+/dsWE5fQPySONavBBJ8wqExj0xKsNx0Q9tRdRmHpgG4aV74vguwBDU0CVODNRncW03BHDClqBb/xz9SHKXQEaoBzCE="
#mob_test_aws_secret_access_key
  - secure: "Zrbv1R4qSCc/1vQEFRZ1UMTEEYxyLJKUzGnx7T/zex7fszQlhHEiZZuCH/5yWNkrPeApqR47Tw+oLhiWFw+Yivk4xEBji8VVrRec0ZT/ZkX2kH1ykE+E3blpzeWHRPKn68ZD56uK409NW5f3BVvNzdju47IGXHvHkq2llBXsESA="
#mob_test_ec2_keypair_name
  - secure: "meMH/Z03JtnPIgkSkUOoJhgsbsM6613w8XMZ8t9p/+P23M9q1ioMhWyzOCluSE9kbOUvcibjPUl4D4cC42KXoeL6Y3y0zO78w5LIxVhCV0OPx9hLPX9CkLWm2ySg0ECQcg4siXP+EZF3NYI/sZm5/LyfT9sgGnyvyopPzBb6qY8="
#git_ssh_00
  - secure: "FnoCpSbl9IhtgmxKBO7iYK8vOtKEr+NJN3F9Pt0up/Ln634VrKM8UvB0jz0uolo5b0idNNHkahry7z5xc3RIUINdbn2lEeshgyph8M+RHg8s/kEtM7XyLP+i932qkCHfaCmZkRBer2pZOKFzav1WrMoF+qGaINudZuq1Hx5EWJ4="
#git_ssh_01
  - secure: "mOZ7OR9GOIqu4mRW6Gdtb0/Jb/ko8WOO1DTDJrlVM/LuHeladjxlsP272tYYJLgEIHUmZ57m9ogR9XjK6oi3j8CyPndxk0eC7+QsQPQFlaXPXdwipxNAAiRutgL5qoIuz6R1LlkMSDC3jK5HrgrPKDLNvkih31OqbRGiXnwAhAI="
#git_ssh_02
  - secure: "Fm8FPeSiw67NZRkfNydi5WJF7hpLI/D26Fr6bUcJQV8dQ6hU6ROKNhES0hHomXO9kcAFWkYMTiYc7+bKmMvHn+qZAIF0mY5IsulSlGrv6FAROSdHoKVelVw8Yj+A/FmWC2Mqom24LwlIz2p3THiQbDHXCH691s5+RxTBzqplKOs="
#git_ssh_03
  - secure: "jUuivHl+MR+igB4cFD36WrQcAWaWtI3XlqYJSUiNyuk7HVPmYS1+13Go7wkf2F7NAoY0xbXqSgT8EJ/hiP2XIBRZfuTkD4Olzwp8s23DTJ7Fzk9yXiSoOvpAbv4AHRyg6AiSjFaGG1SgPIk4wnZlHIjicGn4q/pxCawEfSlmH+k="
#git_ssh_04
  - secure: "TgbGSTrug/nqXtA34PXGjAzzHKzDpKHHTGJ9j9ERC4i942dLUNHOrFdTuwcVxKqWgX/EoixxZSU8r707JF0ZcHg9R08MXxx2jIi5ZCUgqoM0IAwOUBr2QritNkBZ3acSdL2FvHmEWNoVwHoHN1YTj/5rJHUqJeQJuNNYEfxrzbc="
#git_ssh_05
  - secure: "hFpmi0nOPu8aBteMeB5tGbZX4Mh3/1Sy1yW4GvF5UOlT1r2SVnSOPUKAdB9iiIS35Or+XFZ6cJyV64CKczoUcspqhcFY9z/1RpHvYKAnK3H+Ns1EYBhnkp6LAb3NtUz6M/OAM8MiuUBUKi1BoeGxKDZrTflsqT4/NQgoXTjBS/0="
#git_ssh_06
  - secure: "TvLrGiRhqTY8/vmdmELZcnfwWO/zzfTTJA+20tfWXFmYxHEhKGKnX8hm3v6+w+8DV4JlR94opzLEaAbTeVt+mRaB/DPqJkutYHHeRikiWM6eGhBdcaRpRiXcL3pwOFfSv8xmQqnyMD2AsEp3EAZRDjEqz1qVjrA4LfBAa49Z3h0="
#git_ssh_07
  - secure: "ndbIkCxbtBm0l6MHSkZ+GgIKfzT8edXIyhezLbuwdtnM0QbmOrrX1Ma/TU/Eo4kA8IRljzu9+dQmor4pnuy02zh3eWc7IK0uId3CYgP5LnnGdbTRuE4DTdJWQOfmmHlVLcr7XObJUaj7dI8exJHI+4vJQRMBFx05AOG2ZmpNWdA="
#git_ssh_08
  - secure: "SBx5f6UM/ruKHiNmqEeeUFkvDjkTBFbjANYwWXDoHh19pAQn0y3tqOYY1VzYYjGelf7IwQdtR25pZ79ZZgLJvUU9PvsNitkmaJWhLpYdI6xb5AXCwdoHsC0o3yxQ8qv420V8LfHEQaHwfcRsy1+ivv8YWTDTER5/bTHIOOQHY9M="
#git_ssh_09
  - secure: "FmdEG0+HDGYSO6b9RzgJ6t3cX27iLmys28bdKIvt8c4XMeBCWiZv4JxACzuh4WuoKCpVAyHPkTzdsv1R+L75TkFzLRteDhQCLjYEb530qdjR02hhXpJwJkfv1/pCCcacqJ3+TKLkiUWBfIEVE+h5BGVtSbGgn4qAuFEiHWZcqy0="
#git_ssh_10
  - secure: "W5tqkE93t6asczJzI/ockdNQD8JCmLzjqIKO+j3jcSQUr0k450g4P72PeRYo/NdKCxnzUaPnz0U4LvhRry3bZzuiQYxb6/BWu9CDdV8s6liwzBoiZlvUa0DTdA4jUdPJwzJieVhZbD5lMvfAU107kHDn8Naurybf19DT1L2CCA0="
#git_ssh_11
  - secure: "dD+lXErMisM5lUN/pNEQirerKh5yCDRn4syQSrnmPEdfwgyCG6AfGBWw9G7Z/OZP+ajFoyfohbjhdb5exDQsH7vTqqtv4McYcVNblRfU427qYuOdOQj7/Ld1JLAPbW/a6jVdqzzRhkE9yC0ArYzMPOcNpH07aIC/GwJ2e9Gf3ZQ="
#git_ssh_12
  - secure: "M0eVAwiWDGJq730YSTlglbJdrZcjQxjRz9TbaWIGdo6PcfHKUVSkDsgOaeylKnHGnRe2wjFI91VKZOPOq+Ozq1TwXeNo8Bg2nKmz/gG3iaIQ9DYH8/DRXmXLT4O9PINa0/RD2c/ebOr81bZUtzSrqighi4GFcyCIRv0cYfsSbQc="
#git_ssh_13
  - secure: "HNpe2pw5GP/r8qpZLfercU90KZ3qbClYz+pZwec62B8Cpaw+GxRuT9f+efV1I6l8Wt6imbuQuHDDRaVSmnnsYel/h1me/YRwYe82FKimcXkVZZr9bZ6HkT5FDBmzPGUYDVzFgHULAQSbdQgMb4Ai2DwfFf7Ac5bhlSYKkh+eVW8="
#git_ssh_14
  - secure: "E0qoro75Vy5RApmQ80kwbDmCdJT37qUgqgyFCJ3ot7PKVuuuW5AT2IIBQLnjoKCuUEGen33rygnsY04hsQa1VEHNVvprbiVXTVyCUmmSVSY5xtPXd427F9XUpWiaEkVKq7tO+OXODWVe7jjdaioAG2UAaLSHJYQ0upzo3cZpT3w="
#git_ssh_15
  - secure: "fNIjfECN3YZ8HM2BC0ediYlBQoSGE/qjZCSHsYFauCLEdQjwUhk2J5kVwqBNRm/ycpeCPZxZvAbPJyFUrqjWlrAciaZvhzS/3Gzkj2ELbQkv+T3BQTYgbW9P5zMenMjazQsRRdYU8Pdbb64k+Ymy+BhApAZNbBK8ZTr9x2GrLZw="
#git_ssh_16
  - secure: "HH3EUVXaaM/5WQH5IUswB/mAx4WtJyzVcZjBBuH+TvQkzx5j3SEMBIU+01WAHY8616YehVRD8Ynll+9iappZ1p3iSIrsv6/jvnROr+wyw8UZOY3EnhHJx5ag+FQ7n7Ge2I+vTofTcqu9H5R21eoDY+BQT9s/MMM3J4rEvAe9DHc="
#git_ssh_17
  - secure: "XY7kLK48Hf5PaRwEjka5BKIcfZRLdDkW6Ro2tTEDq4nHS53S1yOu/sixOuTvN488InWtDU46xmNfn5IRNledV1oJwVnV2wDQepf0x7bzhqAhTOK2GJVCY1waCC7N5Uahh3lqpIolmk68Uf2SkWaEFMKSRT7TQgvTj5LVIei7Ox4="
#git_ssh_18
  - secure: "P1JRRXeYH7jR2dYzMKq4xBb+swH/ncl3h6fTbfqzZNbjdkSTPYCzG38Li5A4tr6lE5seUtpuV3E+yLx+XcdC6xT9+yNvstjsU+XHE9t16kpY5rqiKCVSldMOjtDRS5GOCBoXNvbANDI6WdzVQXey5rc7gOIS58X4EUmMTV30pjg="
#git_ssh_19
  - secure: "U8zglBPX2k50RufhzY6H+XPyGvkIe50OC5QuMrKe9NX8cUhNQDzO+G6EvGEk7Qq/BHJ4wh8dmvABcBs1PNTEKaAWW9Q7sLkDGqXM079t8B31j8ke54rZK8Mrdd7PDOPxG1f7Bqv/1CVjNcTGsS5wYa3sBjvjYtVB8Y5Ie1Lc9SY="
#git_ssh_20
  - secure: "RmzNBjdoL8gslRCujnluxjguuembMUz+oD6m1ix/PMDw9ctwn66b88wvga9yvqGP/ewURyuLYcFZON/h9FU8FgiYAIQ3LMlnJUV/IgbIzqI/SH+B1rJ/oATQMxNrmsYeM/JRHUtaKUXu6JV7U7I8lLwc+0IuCBMLrTq25eoH15k="
#git_ssh_21
  - secure: "flgZK4uLXgZme410hsXUrcw4Wdi9NvdzkjMZz98e5hXQthF33n//axzPdbUzTGeUkuZxKL8vtjlWEQqwcuAt6DDFPs9WPnIkufcA/TJx2DSpPx7D9YDwaeiqqQqM8smLx7lm7eZ7dwD0aLjP4P4srzv05YJ5JdSGgmEwCtDOM68="
#git_ssh_22
  - secure: "SffVNf/OTB9KVmhSsYwQwEbtsLs8kyfM6OrdYD/RPOPIE3yF5ddYWUF0upjE/SH919Uxgt4Er3DsypUaYWh4zyFLnctPTtRj7vmzlF0aQ6r7SwSMmSDYHYKPNRt+WG+Iy3bi/eHZ+QL2a9mugbqiDLuLX/arA4sqmHyvMkmYv/Q="
#ec2_ssh_00
  - secure: "RKwD1juBOWUUYkJGsNz3FIsplV8VCYtJ3X7d/DT2543cnfdrvWSO4HfHBT3mwt8Qd66x3uUlPaRrI7fV2RfWiUKEAlKTW8F0Zx0/QP2RFmfM0LDZJRMkrqDn9Z1De1zcGYZbpawY5Ia2VWZ39L15J05AIYW8JmCUeC5yA3zgXcw="
#ec2_ssh_01
  - secure: "mBjeYUm6NYLiAivYYNQG1FHe1/tIuOabbBncqm8vspUUbuMfE1B+2FuNxOx/E8CAzZGBeMhfxxQOVEl30xg4vpsyY1SuDqDgGptHLfGWAzuWwdAAs6LVFs0MxxTrZjHFbPF89slfC4yEBvggWr5ktJHDFaebTmnQMI7oAhuOONg="
#ec2_ssh_02
  - secure: "n3k45lxpI9ylu8OP00KaRIzUHiVXXzt5gD4K/iFohtmeRsiQRWfC6AtDknnmkmYJfDeq0yVl9nR6BJAlUVhTz70O43qmjoKifpuYEFauAjEGPqF9IndxQggaQ7f28rmxzMyMHMj9tlw09URSLMR/U40uaaWr+ahQ1KRTBaZpf6Y="
#ec2_ssh_03
  - secure: "GvG5mm+gYSZYiJaVxGWn5FeGWa/06mpOgZueLxSIePk5j2oSPRQ2JhM+frssFumZwK4RaWRY+vwFQmxaGROJ1xVx7X7TeVGtJfX5SwRsxmj00+8OE2AO0SS8sk641g2UQFJynX2pwJq768XKkmUL7MlyHrvWfWuuhersTN01vX8="
#ec2_ssh_04
  - secure: "TW5NZUO5qequ9b2DlpHecibLukm/GITR9FWiUij0adl/2+zoZZ37JYMdD51r6wEqI7xxVfBJ/KV6Pd6CWVIgf818AiElwFQCuxte9l9Ie91FTkl4dAP19d8g2KN9PqNqvnlaRErPcDhTWwQcQCfyHp3M87XW3gR9pMfQjwmCwrg="
#ec2_ssh_05
  - secure: "HB3txm5eAiyONaq/PLJhJu3TmWXlsjLl0Xim5Jaw6WGRKizIv/ncmmAM51lFT+zvjWq6HvGW+TnmEa26Tzk4sjVNPa4DsEyt0r9yvqH+9bYZHaBsrSiPHMJ11Sxhf8whi4KftuZqFJd09KeTwivGoOY2j9qQP1jZW9JE+l6G29o="
#ec2_ssh_06
  - secure: "dJe91Un47t0ZeyNzCz+7sGisbzdg9LVYCaIkDajVYcgK28xpU70rWKju0G38lVwGTI87Yl2ZsiaR3Qeo2li3mYZ5tsQuLcQKvEQnyGRryS3WQJykGbIfZ5ld8lJphu3DBVTDYeobDe+r48zT1Lbj6m1FZ6oaMX55hOgFLcA2ePg="
#ec2_ssh_07
  - secure: "AR3936dDXpZVbFQ9cX2wRVXT1gotRH85E3hT9EfTW5NTxPQ1ivk4OZsVxED3FTXpbSSfAdPfWwvA2S5O0gY4n13TurjS5mDegHm5StHXe5pWFzftDoh3ADR3xGFrkhj/7F31EwvVwKJovod7z4lfw52j2XhvT9oNMN9DqexPGs4="
#ec2_ssh_08
  - secure: "Uy+MWHdLK3nlnaRDpRp5MX8+B5X6x/2ENint0vRibeEdnas7fuI22MsU8TIcjbDEWjgCZmGc12ks5BR/tZfyqt0tq1wiDY26YePFq/pOF9Rcyem/LHzv8eWyTh6I2es7fbFaqgvSJ+Bw1qthr8dNOi5di6yEPygriBrM7KgIa7k="
#ec2_ssh_09
  - secure: "XvB3KvStzIbHB/4Cd2/G36UmuWX7j+IHw0//QXQLFGC60Z28uF0Xi0Da9gQ5zAWx0xF/wSD2po423gCWAEKBG0VjagvkqcL/dQChlCdNiua8dnXhilNHGL231FDGWBmcasTsj5Mvrep6nldwizxExn3vl6LPeDYJPEeDxHAmRXk="
#ec2_ssh_10
  - secure: "K7Np+gMSjwl5KJKBhtqI8Db/ABNH3uSR+8cohiHE0ehYe8QLtgU5ixspbZZhTgLdXY098KvSokVaiFJg5a9esHTu592suyzW6T6dCX3Xvjvhnnty6u5aRBDwmoewXjDuWc2LKi3boiEeNRiIg1rReFIga7hFL5qaT5DlpISKAak="
#ec2_ssh_11
  - secure: "lV8Q/YvoBmD5s8vU32uKozXVsnlFtE5iOQCEoP+Vnqeh7t5vnsJu0HKVy8Rvg7OqJkz5ckayf+7p3RzGzJb7xiPWblN/1ru7HtM9L9vpIRFQHWnbH69N57Gutm2ZEcziyesinGXPzGIbn216Ft59Cqr82MfpB8PSxF4iIG8qmr0="
#ec2_ssh_12
  - secure: "ZZWKNb7o+v3WDd8p/XXChpI59uq14ZHKTdhjirE4Dyy1qZCb8TxWrjXEZ4hguaaZKhMlzuUIoOZMj0dYR/OQH4rhpZWv8cqi8STAu/m4lNS+yqv9dpM+aSvYEl4vIUSZxCJoPx+pW1fdRw2TcF+Tq2UXdvww7e4K+z9NoC3DiEI="
#ec2_ssh_13
  - secure: "NP5m3eBPifK0m/9JNngN76z3tnKDi8W2cHtgftYGwnznjlmatMtfLyqd1U/CMYRcBqKppf1MTutS9Nm+tfe1NsUetN7IKeNns1W9suMelhIe8qycZdOk6QacNg7eh++ZRWCzcYKwCOy2KJomKH9ap/jOCSl/aTvDGk9O315+5k4="
#ec2_ssh_14
  - secure: "XjnPoYbCXgVPPCZ0C3LqDXCfCBxBeNDhIxIJbwlrEiYh52oL2y9jvixnBShqji08hAi9iVWDJaHLvdcsTnI5vPD7jlnOgveI9Sp2gBf5jVr6sPokU0KppmVDf40jSkbF4PVi/Bf3/1l0/nZzsIRT0Z2P5aAg9xwjG5huB+tRcGo="
#ec2_ssh_15
  - secure: "CWbJXy5LMHwkVvG4ZxLNpaykCwkyCrVChOj9J1XIP2OzVU4r5/Zex3MLa3xl8aAAq0u+ZeapwTDGtUtx5v/0mOTa4b7qKXzrBo934MD70djkD5Qkpnl1JWNUlChJkLr9/d8ZQT9n8NAthQAvcBzuLuOZTgsu9aTmw9vYBh7qnsM="
#ec2_ssh_16
  - secure: "Y/sDAiNLDDqBLRoBLpr9576gQGwLCdVih+gVSRx4TwENO1wyWbXDpUGo7aiWlB4gVdzZLMcN1jpbujk8mC4CLBh8bdBFM03SobPiYMhZGT7VxgxnJCDDE1m3ep9g9SFl3SoPrxcfYZ0PNz2MqY9PdrcWJ/Z7d3Wz6pt56uUrL3c="
#ec2_ssh_17
  - secure: "HqvATmxGa0jzOuJtxt5FAR0sM9h0qT2NSn+uGNf4lUh0cDekyT/S+pdL27Lf0jhxWPusrJ6qHnoi9cP/ITF72GQ/YbI4cdYdd/pWVVxrKem5kw2/tnDkHJ6XkYhTZDvm/sBj7OE9hFwSiKjEKcqDUF4Z7BRh7o9EbtMndbzx8r0="
#ec2_ssh_18
  - secure: "UB9giBDtMt+Zvu0I1/ZwR/2wQkWS2ZD8jiaUUCxLOxRLoa5sobaCUt2t7AnuMDL//wds3dlv1scrN8EPQieRjUuE2XsS5KrojPaIUHCt9VlxcQvCXfUD6Y1aXUdaFmuvuUevLuR7jwZ/YiyDUzMrjrnzwvdsHTDS8pixcta9C5Y="
#ec2_ssh_19
  - secure: "nwhhJlucV9WizcPhy7ITIlgHSW3i0LsCc0fvNcxOaBNPvscO/FpmIPi+LkESGqAtVBbLOxC/q1fiBbdl8YiPQ+OwK5ZDaH9EU/82qAaTHRXHfuJlKwrYOnbZyK9rbKDbl1eD7/ZChILlOtt1hRk0ifxF9HcZS+yFDPsl2/BPIzU="
#ec2_ssh_20
  - secure: "dEYOIUuRhp0KF8fAoRlxVkl76FNF1R/NVZxxpsuA7tbdYwIa997dFtpuWQOclmFP3uKIXm+SdvsVH4d5e07fMJBTlBeJWZIspO6bjh9BqAx9RhQipP2P0E/hsgLLy3CUYq2+A5LBN8F3whtIVH1L0pGX054F18a/1GBFmDVYHLU="
#ec2_ssh_21
  - secure: "L87PqKTlHo8VdISoemSVyZXJoe43g22OwXRwbA+h4EwmZYybqe2syvFTJT2G//Dut9tHFLCqkgiVUezqG/hZ78gJUwRs2MA55HfbJvBxdBFBrkjQyYZ5xuMa4aguKM3pTvFAeppVs/43eqqeuDWrM0FcdcKKWs3xcPVSYsNMVAc="
#ec2_ssh_22
  - secure: "eooQwuYrgorsv36rHNiHldWUnsV7s147+HrPvjr1t71ZLwy6c6KaoMc800jX7RUe4ryo33eMhV6GfROD34Hn7N8DeVxldUDt97je9F2WwEY7tb33DDpOCuUznylx7OEvtrirljHNAsniq2D1RRV+y+MNe2KTWBdJ9LVWEk4GFsk="
#ec2_ssh_23
  - secure: "juCbLwT06bXCNs+eh4L/3dVBH9ANc0CgDIuBHx3g/wSsfaCcP4MoZLNQLeIDlEHEWBs67aXWyBMNFgDetrelChjYiWl6z7zg+m1Fe630Q2j8SLIZ9t1DvXdkQKBo0u6yT7HXkeSkgFig9MuWpVxB3mKKihewBeFLhjJYOJP+oyk="
#mob_test_google_login
  - "MOB_TEST_GOOGLE_LOGIN=mobilize.server@gmail.com"
#mob_test_user_id
  - "MOB_TEST_USER_ID=mobilize.server@gmail.com"
#mob_test_github_login
  - "MOB_TEST_GITHUB_LOGIN=mobilize"
#mob_test_owner_github_login
  - "MOB_TEST_OWNER_GITHUB_LOGIN=mobilize"
#mob_test_private_github_domain
  - "MOB_TEST_PRIVATE_GITHUB_DOMAIN='github.com'"
#mob_test_private_github_owner
  - "MOB_TEST_PRIVATE_GITHUB_OWNER='mobilize'"
#mob_test_ec2_def_region
  - "MOB_TEST_EC2_DEF_REGION='us-west-1'"
#mob_test_ec2_name
  - "MOB_TEST_EC2_NAME='mobilize-test'"
#mob_test_ec2_ami
  - "MOB_TEST_EC2_AMI='ami-fe002cbb'"
#mob_test_ec2_size
  - "MOB_TEST_EC2_SIZE='t1.micro'"
#mob_test_ec2_sg_names
  - "MOB_TEST_EC2_SG_NAMES='default'"
#mob_test_ec2_root_user
  - "MOB_EC2_ROOT_USER='ubuntu'"
