development:
  master:
    email: ENV['MOB_MASTER_EMAIL']
    pw: ENV['MOB_MASTER_PW']
    ext_ips: ENV['MOB_MASTER_EXT_IPS']
    int_ips: ENV['MOB_MASTER_INT_IPS']
  worker:
    ext_ips: ENV['MOB_WORKER_EXT_IPS']
    int_ips: ENV['MOB_WORKER_INT_IPS']
  poller:
    ext_ips: ENV['MOB_POLLER_EXT_IPS']
    int_ips: ENV['MOB_POLLER_INT_IPS']
test:
  master:
    email: ENV['MOB_MASTER_EMAIL']
    pw: ENV['MOB_MASTER_PW']
    ext_ips: ENV['MOB_MASTER_EXT_IPS']
    int_ips: ENV['MOB_MASTER_INT_IPS']
  worker:
    ext_ips: ENV['MOB_WORKER_EXT_IPS']
    int_ips: ENV['MOB_WORKER_INT_IPS']
  poller:
    ext_ips: ENV['MOB_POLLER_EXT_IPS']
    int_ips: ENV['MOB_POLLER_INT_IPS']
production:
  master:
    email: ENV['MOB_MASTER_EMAIL']
    pw: ENV['MOB_MASTER_PW']
    ext_ips: ENV['MOB_MASTER_EXT_IPS']
    int_ips: ENV['MOB_MASTER_INT_IPS']
  worker:
    ext_ips: ENV['MOB_WORKER_EXT_IPS']
    int_ips: ENV['MOB_WORKER_INT_IPS']
  poller:
    ext_ips: ENV['MOB_POLLER_EXT_IPS']
    int_ips: ENV['MOB_POLLER_INT_IPS']
